### ISSUE TITLE
Partial orders are defined using a <= (or <) relation with result true/false

### ISSUE THREAD

**Issue by denisrosset** [paulp/psp-std#1]
Hi @paup,

I had a look at your definition of `PartialOrder`. Actually the relations x < y, x > y, x <= y, x >= y have regular boolean results, as x < y is false whenever x >= y and when x and y cannot be compared.

In Spire, we recently implemented `PartialOrder`, [here](https://github.com/non/spire/blob/master/core/src/main/scala/spire/algebra/PartialOrder.scala), and encode the result of `partialCompare` in a `Double`, using `Double.NaN` to represent the case when x and y cannot be compared.

Have a look!

Denis

**Comment by paulp** [comment]
I'm making some command decisions in the interests of shipping something. Closing this for now, may revisit.
