### ISSUE TITLE
REPL output for README splitAt example

### ISSUE THREAD

**Issue by dwijnand** [paulp/psp-std#206]
The very first example `val xs = 1 to 20 splitAt 10` is currently outputting:

```scala
xs: Split[Int] = Split(Taken(IdView(IdView([ 1, 2, 3, ... ])),10),Dropped(IdView(IdView([ 1, 2, 3, ... ])),10))
```

rather than the more pleasant output in the README

```scala
xs: Split[Int] = Split([ 1, 2, 3, ... ], [ 11, 12, 13, ... ])
```

**Comment by paulp** [comment]
Thanks. I added tests for the (current) readme examples in #207.
