### ISSUE TITLE
Could not find a `+` method on `InMap` or `ExMap`

### ISSUE THREAD

**Issue by EECOLOR** [paulp/psp-std#37]
So how do I get stuff in there?

Is there a method that accepts an element and returns a new map?

**Comment by paulp** [comment]
You don't get stuff in there. The In means Intensional. You can't inspect the keys, which most likely don't exist in any case. Think of an InMap as a partial function K => V.

**Comment by EECOLOR** [comment]
I must be having a lack of understanding. I am now using the following:

```scala
newMap = (oldMap :+ key -> value).byEquals.toMap
```
Is there another way?

**Comment by paulp** [comment]
Previous comment is wrt InMap, ExMap is different:

**Comment by paulp** [comment]
In principle ExMap has a + method like the kind you're looking for, but the map stuff is really unfinished.

**Comment by EECOLOR** [comment]
Ahh, ok, no problem.

**Comment by EECOLOR** [comment]
I will leave this one open then. I have a workaround for now.

**Comment by EECOLOR** [comment]
The version from `master` indeed has a `+` method. Instead of accepting a `Pair` it has two parameters. I will close this issue for now.

**Comment by EECOLOR** [comment]
The `+` method does not work. It will not create a new map with the new value
