### ISSUE TITLE
PartialOrder.PCmp seems too big

### ISSUE THREAD

**Issue by Blaisorblade** [paulp/psp-std#4]
I've looked at #1 and https://github.com/paulp/psp-std/blob/ceaa91a1a52ca28b719b712062c4248a357ed52c/std/src/main/scala2.11/PartialOrder.scala, and I want to open what seems a separate issue:

I'd be happy with something isomorphic to Option[Cmp], but why should `partialCompare` ever return LE or GE?

The only hint I get is:

> That's not true in constructive logic. I am not looking to collapse all results into true or false, quite the opposite.

So I imagine LE might mean "not GT, but we know nothing more".

However, this abstraction does not show up, for instance, in the Agda's standard library. There are general partial orders, which have no compare function but expose just a relation for doing proofs on it, and *decidable* partial orders (either strict, like `<`, or non-strict, like `<=`), with a compare function `a <=? b` which proves or refutes `a <= b`. (I couldn't find anything in Coq's library either, but I'm not sure I would know how to search for this).

https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary.agda#L147-L154

**Comment by paulp** [comment]
I think this is more sensible now. I'll be even happier when I can defer the whole ball of wax to some other library.
