### ISSUE TITLE
`headOption` as a method on `ViewOps` is missing

### ISSUE THREAD

**Issue by EECOLOR** [paulp/psp-std#44]
If there is an alternative, let me know.

The current use case is that I want to perform a transformation on the first element and return a different value if there is none.

**Comment by EECOLOR** [comment]
In my specific use case, the `def span(p: ToBool[A]): SplitView[A]` supplied the behavior I needed.

**Comment by paulp** [comment]
I'm never going to go for methods like "headOption" because where does it end. There is `zhead` (name may not be ideal but there are a number of methods which utilize an implicit `Empty[A]` and they are presently called things like zfold, zreduce, ...) which works like this:
```
// This failure's intentional - there's no Empty[Int] typeclass to be found.
@ view(5).zhead

Compilation Failed
Main.scala:601: value zhead is not a member of psp.api.View[Int]
view(5).zhead
        ^
@ implicit val emptyInt = Empty(-12345)
emptyInt: Empty.Impl[Int] = psp.std.Empty$Impl@6195ce27

@ view(5).zhead
res5: Int = 5

@ view[Int]().zhead
res6: Int = -12345
```

**Comment by paulp** [comment]
There are also methods on SplitView to manipulate the sides separately:
```
@ println(((0 to 10).m splitAt 3 mapRight (_.tail.reverse) rejoin) force)
[ 0, 1, 2, 10, 9, 8, 7, 6, 5, 4 ]
```

**Comment by refried** [comment]
SplitView mapRight/Left sounds pretty handy.
