### ISSUE TITLE
It would be nice if `View` had an apply method

### ISSUE THREAD

**Issue by EECOLOR** [paulp/psp-std#46]
We need this for some cases of type inference. It's implementation can be simple:

```scala
object View {
    def apply[A](a: A*):View[A] = Direct(a: _*).force
}
```

You might even have a better idea for the implementation of above.

**Comment by paulp** [comment]
It exists now (how speedy I am) the implementation is actually `xs drop index.sizeExcluding head` which lets something like this use a few billion times less memory than forcing it would.
```
@ 0 to MaxInt apply MaxInt - 5
res11: Int = 2147483642
```

**Comment by paulp** [comment]
Oh how funny, I totally misread this ticket. In that case it already exists much sooner than this did. It's just called view.
```
@ view(1, 2, 3)
res12: View[Int] = psp.std.LinearView@76b50310
```

**Comment by paulp** [comment]
...and the implementation is +/- what you suggested. `def view[A](xs: A*): View[A] = xs.toVec.m`
